version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    container_name: repair-business-donations
    command: tail -f /dev/null
    tty: true
